#!/bin/bash

# Below is a list of the packages that will be installed
#
# hyprland: This is the Hyprland compositor
# kitty: This is the default terminal
#
# Requirements for hyprland to work correctly
# pipwire
# mako
# wireplumber
# xdg-desktop-portal-hyprland
# polkit-kde-agent
# qt5-wayland
# qt6-wayland
#
# waybar: Waybar now has hyprland support
#
#
#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then 
    echo -e "yay was located, moving on.\n"
    yay -Suy
else 
    echo -e "yay was not located, please install yay. Exiting script.\n"
    exit 
fi


### Install the above packages ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    yay -S --noconfirm hyprland kitty waybar \
	mako pipewire wireplumber xdg-desktop-portal-hyprland polkit-kde-agent qt5-wayland qt6-wayland

    
    # Clean out other portals
    echo -e "Cleaning out conflicting xdg portals...\n"
    yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi


### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    #cp -R hypr ~/.config/
    #cp -R kitty ~/.config/
    #cp -R mako ~/.config/
    #cp -R waybar ~/.config/
    
    # Set some files as exacutable 
    #chmod +x ~/.config/hypr/xdg-portal-hyprland
    #chmod +x ~/.config/waybar/scripts/waybar-wttr.py
fi
